'use client';
import {useRouter} from 'next/navigation';
import {useMemo, useState} from 'react';
import {createClient} from '@/lib/supabase/client';
import {slugify} from '@/lib/utils';
import type {Category, Product} from '@/lib/types';

export default function ProductForm({product, categories}: {product?: Product; categories: Category[]}) {
  const router = useRouter();
  const [images, setImages] = useState<string[]>(product?.images ?? []);
  const [specs, setSpecs] = useState<[string,string][]>(Object.entries(product?.specs ?? {Voltage: '220V'}));
  const [error, setError] = useState('');
  async function upload(files: FileList | null) { if (!files?.length) return; const supabase = createClient(); const next = [...images]; for (const file of Array.from(files)) { const path = `${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9.\-_]/g, '')}`; const {error} = await supabase.storage.from('product-images').upload(path, file); if (!error) { const {data} = supabase.storage.from('product-images').getPublicUrl(path); next.push(data.publicUrl); } } setImages(next); }
  async function submit(formData: FormData) { setError(''); const name_en = String(formData.get('name_en') ?? ''); const payload = {name_en, name_fa: formData.get('name_fa'), name_ar: formData.get('name_ar'), description_en: formData.get('description_en'), description_fa: formData.get('description_fa'), description_ar: formData.get('description_ar'), slug: formData.get('slug') || slugify(name_en), category_id: formData.get('category_id'), featured: formData.get('featured') === 'on', published: formData.get('published') === 'on', images, specs: Object.fromEntries(specs.filter(([k]) => k.trim()))}; const res = await fetch(product ? `/api/admin/products/${product.id}` : '/api/admin/products', {method: product ? 'PUT' : 'POST', headers: {'Content-Type': 'application/json'}, body: JSON.stringify(payload)}); if (!res.ok) setError((await res.json()).error ?? 'Save failed'); else router.push('/admin/products'); }
  const title = useMemo(() => product ? 'Edit product' : 'New product', [product]);
  return <form action={submit} className="grid gap-4 rounded-3xl border border-white/10 bg-white/[.04] p-6"><h2 className="text-2xl font-black">{title}</h2>{['name_en','name_fa','name_ar','slug'].map((name) => <input key={name} name={name} defaultValue={(product as unknown as Record<string,string>)?.[name] ?? ''} required={name !== 'slug'} placeholder={name} className="rounded-xl bg-white/10 px-4 py-3"/>)}{['description_en','description_fa','description_ar'].map((name) => <textarea key={name} name={name} defaultValue={(product as unknown as Record<string,string>)?.[name] ?? ''} placeholder={name} className="rounded-xl bg-white/10 px-4 py-3"/>)}<select name="category_id" defaultValue={product?.category_id ?? ''} className="rounded-xl bg-zinc-900 px-4 py-3"><option value="">No category</option>{categories.map((c) => <option key={c.id} value={c.id}>{c.name_en}</option>)}</select><input type="file" multiple accept="image/*" onChange={(e) => upload(e.target.files)} /><div className="flex flex-wrap gap-2">{images.map((img, i) => <button type="button" key={img} onClick={() => setImages(images.filter((_, idx) => idx !== i))} className="rounded bg-white/10 px-3 py-2 text-xs">Image {i + 1} x</button>)}</div><div className="grid gap-2">{specs.map(([k,v], i) => <div key={i} className="grid grid-cols-2 gap-2"><input value={k} onChange={(e) => setSpecs(specs.map((s, idx) => idx === i ? [e.target.value, s[1]] : s))} className="rounded-xl bg-white/10 px-4 py-3"/><input value={v} onChange={(e) => setSpecs(specs.map((s, idx) => idx === i ? [s[0], e.target.value] : s))} className="rounded-xl bg-white/10 px-4 py-3"/></div>)}<button type="button" onClick={() => setSpecs([...specs, ['', '']])} className="rounded-xl bg-white/10 px-4 py-3">Add spec</button></div><label><input name="featured" type="checkbox" defaultChecked={product?.featured}/> Featured</label><label><input name="published" type="checkbox" defaultChecked={product?.published ?? true}/> Published</label><button className="rounded-xl bg-[#C9922A] px-4 py-3 font-black text-black">Save</button>{error && <p className="text-red-300">{error}</p>}</form>;
}
